server:
  port: 9999
spring:
  application:
    name: demo-eureka
  boot:
    admin:
      url: http://localhost:${server.port}
  jackson:
    serialization:
      indent_output: true
  aop:
    auto: true
endpoints:
  health:
    sensitive: false